queue_rules:
  - name: main queue
    merge_method: squash
    commit_message_format:
      title: pr-title
      body: pr-body
      trailers:
        - approved-by
        - merged-by
    merge_conditions:
      - check-success = all
    branch_protection_injection_mode: none
    queue_conditions:
      - check-success = all_light
      - check-success = pre-commit.ci - pr
      - approved-reviews-by >= 1
    draft_bot_account: mergify[bot]
    merge_bot_account: mergify[bot]
    update_bot_account: mergify[bot]
