repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
    exclude: \.svg$|LICENSE
    log_file: log_precommit_trailing-whitespace
  - id: end-of-file-fixer  # add EOF "\n" if missing
    log_file: log_precommit_end-of-file-fixer
    exclude: \.svg$|LICENSE
  - id: check-merge-conflict
    log_file: log_precommit_check-merge-conflict

  - id: check-executables-have-shebangs
    log_file: log_precommit_check-executables-have-shebangs

  - id: check-shebang-scripts-are-executable
    log_file: log_precommit_check-shebang-scripts-are-executable

  - id: check-added-large-files
    args: ['--maxkb=50']
    log_file: log_precommit_check-added-large-files

  - id: check-case-conflict
    log_file: log_precommit_check-case-conflict

  - id: check-symlinks
  #- id: check-xml
  - id: check-yaml
    args: [--unsafe]
    log_file: log_precommit_check-yaml

  - id: detect-private-key
    log_file: log_precommit_detect-private-key

  #- id: pretty-format-json

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: "v1.5.5"
  hooks:
  - id: forbid-tabs
    exclude: Makefile|\.gitmodules
    log_file: log_precommit_forbit-tabs
  - id: remove-tabs
    exclude: Makefile|\.gitmodules
    log_file: log_precommit_remove-tabs

#- repo: https://github.com/cheshirekow/cmake-format-precommit
#  rev: v0.6.10
#  hooks:
#  - id: cmake-format
#  - id: cmake-lint

#- repo: https://github.com/codespell-project/codespell
#  rev: "v2.3.0"
#  hooks:
#  - id: codespell

#- repo: https://github.com/shellcheck-py/shellcheck-py
#  rev: "v0.10.0.1"
#  hooks:
#  - id: shellcheck

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.6
  hooks:
  - id: check-github-workflows
    log_file: log_precommit_check-github-workflows


# Clang format the codebase automatically
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v19.1.7
  hooks:
  - id: clang-format
    types_or: [c++, c, cuda]
    log_file: log_precommit_clang-format


- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
    args: [--line-length=100]
    log_file: log_precommit_black

- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort
      log_file: log_precommit_isort

#- repo: https://github.com/johnor/pre-commit-lizard
#  rev: 'v1.17.10'
#  hooks:
#    - id: lizard-cpp


#- repo: https://github.com/rhysd/actionlint
#  rev: v1.7.7
#  hooks:
#    - id: actionlint

- repo: local
  hooks:
    - id: doxygen_header
      name: "Check doxygen headers"
      entry: python buildbot/check_doxygen_fileheader.py
      language: python
      pass_filenames: false

    - id: license_check
      name: "Check license headers"
      entry: python buildbot/check_licencing.py
      language: python
      pass_filenames: false

    - id: pragma_once_check
      name: "Check #pragma once"
      entry: python buildbot/check_pragma_once.py
      language: python
      pass_filenames: false

    - id: check_sycl_include
      name: "Check SYCL #include"
      entry: python buildbot/check_sycl_include.py
      language: python
      pass_filenames: false
