import os
import sys

print("Current working directory:", os.getcwd())
comp_db = open("compile_commands.json", "r")
db = comp_db.read()

print("Database opened, replacing non standard flags ...")

db = db.replace("--acpp-targets='omp'", "")
# print(db)


def remove_plugin_flags(cmd):
    new_cmd = ""

    for a in cmd.split():
        if not (a.startswith("-fplugin=") or a.startswith("-fpass-plugin")):
            new_cmd += a
            new_cmd += " "

    # print(new_cmd)

    return new_cmd


def remove_pch_use_flags(cmd):
    # With SHAMROCK_USE_PCH the translation units are compiled with
    # `-Xclang -include-pch -Xclang <file>.pch -Xclang -include -Xclang <file>`. The precompiled
    # header may not be built (or built by another clang version), so drop the -include-pch part,
    # the header is then force-included textually through the remaining -include.
    args = cmd.split()
    new_args = []
    i = 0
    while i < len(args):
        if (
            args[i] == "-Xclang"
            and i + 3 < len(args)
            and args[i + 1] == "-include-pch"
            and args[i + 2] == "-Xclang"
        ):
            i += 4
            continue
        new_args.append(args[i])
        i += 1
    return " ".join(new_args) + " "


def is_pch_generation(entry):
    # translation units generated by CMake to build the precompiled headers
    return entry["file"].endswith("cmake_pch.hxx.cxx")


def remove_external_files():
    global db

    import json

    dic = json.loads(db)

    ret_dic = []

    for a in dic:
        if not ("Shamrock/external" in a["file"]) and not is_pch_generation(a):
            cmd = a["command"] + " --acpp-dryrun"
            # print("--->",cmd)
            new_cmd = os.popen(cmd).readlines()[0][:-1]
            a["command"] = remove_pch_use_flags(remove_plugin_flags(new_cmd))
            ret_dic.append(a)

    db = json.dumps(ret_dic, indent=4)


print("Removing external files ...")
remove_external_files()

print("Creating clang-tidy.mod directory ...")
try:
    os.mkdir("clang-tidy.mod")
except:
    pass

print("Writing compile_commands.json to clang-tidy.mod directory ...")
comp_db = open("clang-tidy.mod/compile_commands.json", "w")
comp_db.write(db)

print("Done !")
