name: Acpp/clang (Clang-tidy)


on:
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  shamrock_acpp_omp_tidy:
    name: AdaptiveCpp omp tidy clang-${{ matrix.clang }}
    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.container }}


    strategy:
      matrix:
        include:
          - clang: 18
            cuda: 11.0.2
            rocm: 5.4.3
            container: ghcr.io/shamrock-code/shamrock-ci:ubuntu20
    #if: false

    timeout-minutes: 60
    steps:
      #### Checkout part ####
      # Checkout merge commit if PR otherwise default
      - name : Reconfigure git
        run:  |
          git config --global --add safe.directory '*'
          git config --global --list
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          fetch-depth: 0
          submodules: recursive
          ref: "refs/pull/${{ github.event.number }}/merge"

      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request_target'
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Show diff against main
        if: github.event_name == 'pull_request_target'
        run: git diff ${{ github.event.pull_request.base.sha }} HEAD
      #### End Checkout part ####

      - name: ls local
        run : ls -la

      - name: install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{matrix.clang}}
          sudo apt install -y libclang-${{matrix.clang}}-dev clang-tools-${{matrix.clang}} libomp-${{matrix.clang}}-dev
          if [[ "${{matrix.clang}}" == "16" ]]; then
            sudo rm -r /usr/lib/clang/16*
            sudo ln -s /usr/lib/llvm-16/lib/clang/16 /usr/lib/clang/16
          fi


      - name: configure Shamrock
        run: |
          ./env/new-env --machine debian-generic.acpp --builddir build -- --backend omp

      - name: Configure
        shell: bash # In docker container github action default to sh
        # we need to run shamconfigure twice because compile_commands is not generated otherwise
        # with this docker image, i never saw this behavior before
        run: |
          cd build
          source ./activate && shamconfigure && shamconfigure

      - name: Generate version file
        run: |
          cd build
          ninja src/shamrock/CMakeFiles/shamlib.dir/version.cpp.o

      - name: Copy DB
        run: |
          ls build
          python3 ./buildbot/make_clang_tidy_db.py

      - name: Install clang-tidy
        run: |
          sudo apt install clang-tidy-${{matrix.clang}}

      - name: Run clang-tidy
        run: |
          run-clang-tidy-${{matrix.clang}} -p build/clang-tidy.mod -use-color -config-file .clang-tidy -export-fixes clang-tidy_results.yaml -extra-arg-before="-Wno-unused-command-line-argument"

      - name: Run clang-tidy-diff
        if: >
          (github.event_name == 'pull_request_target' ||
            github.event_name == 'pull_request')
        run: git diff ${{ github.event.pull_request.base.sha }} HEAD |
          clang-tidy-diff-${{matrix.clang}}.py -j $(nproc) -clang-tidy-binary clang-tidy-${{matrix.clang}} -path build/clang-tidy.mod -p1 -config-file .clang-tidy -extra-arg-before="-Wno-unused-command-line-argument" -fix 2>&1 | tee clang-tidy-output.txt

      - name : Generate diff
        if: >
          (github.event_name == 'pull_request_target' ||
            github.event_name == 'pull_request')
        run: git diff > diff-clang-tidy && cat diff-clang-tidy

      - name: Print clang-tidy output
        if: >
          (github.event_name == 'pull_request_target' ||
            github.event_name == 'pull_request')
        run: |
          python3 buildbot/clang_tidy_diff_report.py -i clang-tidy-output.txt -f diff-clang-tidy -o report_clang_tidy.md

      - uses: actions/upload-artifact@v4
        if: >
          (github.event_name == 'pull_request_target' ||
            github.event_name == 'pull_request')
        with:
          name: report_clang_tidy
          path: ./report_clang_tidy.md
