name: Acpp/ Apple clang (Macos)


on:
  workflow_call:

  #push:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  #schedule:
  #  # At 02:00 on Monday, Wednesday, and Friday.
  #  - cron:  '0 2 * * 1,3,5'

jobs:


  shamrock_acpp:
    name: AdaptiveCpp ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]

    timeout-minutes: 60
    steps:
      #### Checkout part ####
      # Checkout merge commit if PR otherwise default
      - name : Reconfigure git
        run:  |
          git config --global --add safe.directory '*'
          git config --global --list
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          fetch-depth: 0
          submodules: recursive
          ref: "refs/pull/${{ github.event.number }}/merge"

      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request_target'
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Show diff against main
        if: github.event_name == 'pull_request_target'
        run: git diff ${{ github.event.pull_request.base.sha }} HEAD
      #### End Checkout part ####

      - name: ls local
        run : ls -la

      - name: install dependencies
        run: |
          set +e
          brew update
          brew install cmake libomp boost open-mpi adaptivecpp
          set -e

      - name: Setup env
        run : ./env/new-env --machine macos-generic.acpp --builddir build --

      - name: Configure
        run: |
          cd build
          source ./activate && shamconfigure

      - name: Configure sham install
        run: |
          cd build
          source ./activate &&  \
            cmake . -DCMAKE_INSTALL_PREFIX=$(pwd)/install_test

      - name: Build & install
        run: |
          cd build
          source ./activate && shammake install

      - name: Pull reference files
        run: |
          cd build
          git clone https://github.com/Shamrock-code/reference-files.git

      - name: run Shamrock Unittests world_size = 1
        run: |
          cd build
          ./shamrock_test --smi-full  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi

      - name: run Shamrock Unittests world_size = 2
        run: |
          cd build
          mpirun --oversubscribe -n 2 ./shamrock_test --smi-full  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi

      - name: run Shamrock Unittests world_size = 3
        run: |
          cd build
          mpirun --oversubscribe -n 3 ./shamrock_test --smi-full  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi

      - name: run Shamrock Unittests world_size = 4
        run: |
          cd build
          mpirun --oversubscribe -n 4 ./shamrock_test --smi-full  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi


      - name: Try starting Shamrock (installed version)
        run: |
          cd build/install_test/bin
          ls ..
          LD_LIBRARY_PATH=../lib64:$LD_LIBRARY_PATH ./shamrock --smi --sycl-cfg 0:0
